steps:
  # 1️⃣ Empacotar o Spring Boot em um JAR
  - name: 'maven:3.8.8-eclipse-temurin-17'
    entrypoint: 'mvn'
    dir: 'acervo-api'
    args: ['clean', 'package', '-DskipTests']

  # 2️⃣ Construir a imagem Docker a partir da subpasta acervo-api
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'acervo-api'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '-f', 'Dockerfile',
      '.'
    ]

  # 3️⃣ Enviar imagem ao Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA']

  # 4️⃣ Implantar no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'acervo-api',
      '--image', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '--region', 'southamerica-east1',
      '--allow-unauthenticated',
      '--platform', 'managed'
    ]

images:
  - 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA'
