steps:
  # 1. Empacotar o Spring Boot em um JAR (Executado DENTRO da subpasta 'acervo-api')
  - name: 'maven:3.8.3-jdk-17'
    entrypoint: 'mvn'
    dir: 'acervo-api'
    args: ['clean', 'package', '-DskipTests']

  # 2. Construir a Imagem do Docker (Contexto ajustado para a subpasta)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '-f',
      'acervo-api/Dockerfile', # O Dockerfile está DENTRO de acervo-api
      'acervo-api'             # O contexto do build (o código) é a pasta acervo-api
    ]

  # 3. Enviar a Imagem para o Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA']

  # 4. Implantar a nova Imagem no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'acervo-api', # <--- SEU NOME DE SERVIÇO EXISTENTE
      '--image',
      'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '--region',
      'southamerica-east1',
      '--allow-unauthenticated',
      '--platform',
      'managed'
    ]
images:
  - 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA'