steps:
  # 1️⃣ - Empacotar o Spring Boot em um JAR dentro da subpasta 'acervo-api'
  - name: 'maven:3.8.3-eclipse-temurin-17'
    entrypoint: 'mvn'
    dir: 'acervo-api'
    args: ['clean', 'package', '-DskipTests']

  # 2️⃣ - Construir a imagem Docker usando o Dockerfile dentro da subpasta
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '-f', 'acervo-api/Dockerfile',
      'acervo-api'
    ]

  # 3️⃣ - Enviar a imagem para o Google Container Registry (ou Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA']

  # 4️⃣ - Implantar no Cloud Run (ajuste conforme o nome do serviço e região)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'acervo-api',
      '--image', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '--region', 'southamerica-east1',
      '--allow-unauthenticated',
      '--platform', 'managed'
    ]

images:
  - 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA'
