steps:
  # 1. Empacotar o Spring Boot em um JAR (Executado na RAIZ)
  - name: 'maven:3.8.3-jdk-17'
    entrypoint: 'mvn'
    # A instrução 'dir' é removida, pois o pom.xml está na raiz
    args: ['clean', 'package', '-DskipTests']

  # 2. Construir a Imagem do Docker (Contexto: RAIZ)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '.'  # O ponto significa: "O Dockerfile e o código estão na pasta atual (RAIZ)"
    ]

  # 3. Enviar a Imagem para o Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA']

  # 4. Implantar a nova Imagem no Cloud Run (Mantenha as configs de deploy)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'acervo-api',
      '--image',
      'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA',
      '--region',
      'southamerica-east1',
      '--allow-unauthenticated',
      '--platform',
      'managed'
    ]
images:
  - 'gcr.io/$PROJECT_ID/acervo-api:$COMMIT_SHA'