steps:
  # 1. Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/acervo-api-temp',
      '-f', 'acervo-api/Dockerfile',
      'acervo-api'
    ]

  # 2. Fazer o push da imagem para o Container Registry ou Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/acervo-api-temp']

  # 3. Fazer o deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'acervo-api-temp',
      '--image', 'gcr.io/$PROJECT_ID/acervo-api-temp',
      '--region', 'southamerica-east1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/acervo-api-temp'
