# application-prod.properties

# Vari\u00E1veis v\u00EAm 100% do ambiente do Cloud Run.

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Storage (tamb\u00E9m deve ser uma vari\u00E1vel de ambiente no Cloud Run)
gcp.storage.bucket-name=${GCP_STORAGE_BUCKET}